import React from "react";
import Head from "next/head";
import Header from "@components/Header/Header";
import {useSearchParams} from "next/navigation";
import c from '@styles/Service.module.css'
import Footer from "@components/Footer/Footer";
import Breadcrumbs from "@components/Breadcrumbs/Breadcrumbs";
import Preview from "@pictures/services/id-introduction.png"
import {defServices, defDefects} from "@app/common/samples/services";


const MappedItem = ({items = []}) => items.map(el => <li className={c.item}><span>{el.name}</span><span>{el.price} ₽</span></li>)

const Table = ({children, name = 'Типовые услуги'}) => {
    return (
        <div className={c.table}>
            <h4 className={c.table__header}>{ name }</h4>
            <ul>
                { children }
            </ul>
        </div>
    )
}


const ServiceId = () => {

    const id = useSearchParams().get('id');
    const breads = [
        {
            link: '/',
            name: 'Главная'
        },
        {
            link: '/service',
            name: 'Услуги'
        },
        {
            link: '/service/remont',
            name: 'Ремонт iPhone'
        },
    ]

    return (
        <>
            <Head>
                <title>Catalog</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <main className="wrap">
                <Breadcrumbs items={breads}></Breadcrumbs>
                <section className={c.wrapper}>
                    <div className={c.introduction}>
                        <img src={Preview.src} alt="Preview" />
                        <div className={c.introduction__content}>
                            <h1>Ремонт вашего iPhone в Иркутске!</h1>
                            <p>
                                Проведем диагностику, предложим вариант устранения проблемы, согласуем с вами стоимость,
                                выполним срочный ремонт, протестируем и дадим гарантию на выполненные работы.
                            </p>
                            <button>Изучить каталог</button>
                        </div>
                    </div>
                    <div className={c.table_wrapper}>
                        <Table name="Типовые услуги"><MappedItem items={defServices}></MappedItem></Table>
                        <Table name="Типовые неисправности"><MappedItem items={defDefects}></MappedItem></Table>
                    </div>
                </section>
            </main>
            <Footer></Footer>
        </>
    )
}

export default ServiceId
