import Head from "next/head";
import Header from "@components/Header/Header";
import CatalogHeader from "@components/Catalog/CatalogHeader/CatalogHeader";
import c from "@app/styles/Catalog.module.css";
import Breadcrumbs from "@components/Breadcrumbs/Breadcrumbs";
import Footer from "@components/Footer/Footer";


const breadcrumbsItems = [
    {name :"Главная", link: "/"},
    {name :"Apple", link: "/"},
    {name :"Apple iPhone", link: "/"},
]


export default function Catalog() {
    return (
        <>
            <Head>
                <title>Catalog</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <main className="wrap">
                <Breadcrumbs items={breadcrumbsItems} />
                <section className={[c['section'], c['section--catalog']].join(' ')}>
                    <CatalogHeader />

                </section>
            </main>
            <Footer />
        </>
    );
}
